name: Bug report
description: File a bug report
title: "[Bug] "
labels: [bug]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
      placeholder: E.g. "I cannot Like the video when pressing +"
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: How to reproduce
      placeholder: E.g. go to a /watch page and then click on another video. Then, pressing "+" will not Like the video.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      placeholder: E.g. the video should be Liked after pressing the button
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browser(s) can you reproduce the issue on?
      multiple: true
      options:
      - Chrome
      - Firefox
      - Chromium Edge
      - Opera
      - Vivaldi
      - Brave
      - Safari
    validations:
      required: true
  - type: dropdown
    id: operating-system
    attributes:
      label: What OS does it occur on?
      options:
      - Windows
      - macOS
      - Linux
      - Android
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: What's the version you're running?
      description: Go to the extensions page and copy the version number
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
